# Site
name: "Shanto"
title: "An Artist"
description: "Shanto, A professional PHP, Laravel and WordPress developer"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /
google_analytics: "UA-46278016-1"
disqus: "yhshanto"
twak: "5cc827ee2846b90c57ac2d29"
hire-url: "https://www.upwork.com/o/profiles/users/_~0113eadf4166290f85/"
mailchimp-list: "https://gmail.us20.list-manage.com/subscribe/post?u=d832ab6ac0e013530bbfd22fb&id=adc06e4460"
include: ["_pages"]
permalink: /:title/

# Custom Collections
collections:
  - jobs
  - services
  - testimonials

# Contacts
contacts:
  phone: +880 1917995609
  email: yousuf.hossain.shanto@gmail.com
  web: yhshanto.com

# Socials
socials:
  - name: facebook
    url: https://facebook.com/yhshanto
  - name: github
    url: https://github.com/yousuf-hossain-shanto

# Barands
brands:
  - name: Github
    link: https://github.com/yousuf-hossain-shanto
    logo: https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png
  - name: Upwork
    link: https://www.upwork.com/o/profiles/users/_~0113eadf4166290f85/
    logo: https://www.upwork.com/images/upwork-logo-1200.png
  - name: Envato
    link: https://codecanyon.net/user/wptriangle
    logo: http://assets.stickpng.com/thumbs/5847f374cef1014c0b5e487c.png
  - name: Brand
    link: #
    logo: assets/img/brand/b4.png

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: "assets/images/avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
